FROM docker.io/archlinux:latest
ARG U_ID
ARG G_ID
ARG U_NAME
RUN pacman -Syi --noconfirm
RUN pacman --noconfirm -S sudo platformio-core platformio-core-udev ccls clang nvim openssl python-pip git tmux unzip wget
RUN groupadd -g $G_ID $U_NAME
RUN useradd -u $U_ID -g $G_ID -m -s /bin/bash $U_NAME
RUN echo "$U_NAME  ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
USER $U_NAME
COPY --chown=$U_NAME:$U_NAME .bashrc /home/$U_NAME/
COPY --chown=$U_NAME:$U_NAME .tmux.conf /home/$U_NAME/
RUN mkdir -p  /home/$U_NAME/Coding
RUN mkdir -p  /home/$U_NAME/wrk
RUN git clone https://github.com/LazyVim/starter ~/.config/nvim
COPY --chown=$U_NAME:$U_NAME ccls.lua /home/$U_NAME/.config/nvim/lua/plugins/ 
WORKDIR /home/$U_NAME
CMD /bin/bash
